const Strings = {
  //Fonts
  poppinsItalic: "Poppins_Italic",
  poppinsExtraLight: "Poppins_ExtraLight",
  poppinsLight: "Poppins_Light",
  poppinsBoldItalic: "Poppins_BoldItalic",
  poppinsExtraBold: "Poppins_ExtraBold",
  poppinsExtraBoldItalic: "Poppins_ExtraBoldItalic",
  poppinsExtraLightItalic: "Poppins_ExtraLightItalic",
  poppinsRegular: "Poppins_Regular",
  poppinsSemiBold: "Poppins_SemiBold",
  poppinsMedium: "Poppins_Medium",
  poppinsBlack: "Poppins_Black",
  poppinsBold: "Poppins_Bold",
  RampageMonolineRounded: "RampageMonoline_Rounded",
  SnellRoundhandScript: "Snell Roundhand Script",
  LunaBold: "Luna_Bold",
  LunaBoldItalic: "Luna_BoldItalic",
  LunaExtraBoldItalic: "Luna_ExtraBoldItalic",
  LunaItalic: "Luna_Italic",
  LunaMedium: "Luna_Medium",
  LunaRegular: "Luna_Regular",
  LatoMedium: "Lato-Medium",
  LatoSemiBold: "Lato-Semibold",
  FlamanteRomaMedium: "Flamante_Roma_Medium",
  GofiendaRegular: "Gofienda_Regular",
  knewave: "Knewave",
  BebasNeueRegular: "BebasNeue_Regular",
  ForumRegular: "Forum_Regular",
  CinzelRegular: "Cinzel_Regular",
  BebasNeueBook: "BebasNeue_Book",
  Brusher: "Brusher",
  BirdsOfParadise: "Birds of Paradise",
  MontserratBold: "Montserrat_Bold",
  MontserratExtraBold: "Montserrat_ExtraBold",
  MontserratMedium: "Montserrat_Medium",
  MontserratSemiBold: "Montserrat_SemiBold",

  MontserratRegular: "Montserrat_Regular",
  MontserratBlack: "Montserrat_Black",
  MontserratItalic: "Montserrat_MediumItalic",
  AntonRegular: "Anton_Regular",
  CourierPrimeBold: "CourierPrime_Bold",
  MerriweatherRegular: "Merriweather_Regular",
  RubikLight: "Rubik_Light",
  RubikRegular: "Rubik_Regular",
  RubikMedium: "Rubik_Medium",
  RubikBold: "Rubik_Bold",
  MyriadProRegular: "Myraid Pro Regular",
  MyriadProBlack: "Myraid Pro Black",
  MyriadProBold: "Myraid Pro Bold",
  MyriadProLight: "Myraid Pro Light",
  OpenSansBoldItalic: "OpenSans_BoldItalic",
  OpenSansBold: "OpenSans_Bold",
  OpenSansRegular: "OpenSans_Regular",
  RobotoThin: "Roboto_Thin",
  RobotoRegular: "Roboto_Regular",
  RobotoBold: "Roboto_Bold",
  RobotoLight: "Roboto_Light",
  RobotoMedium: "Roboto_Medium",
  RobotoBlackItalic: "Roboto_BlackItalic",
  RobotoLightItalic: "Roboto_LightItalic",
  RobotoBoldItalic: "Roboto_BoldItalic",
  LatoBold: "Lato_Bold",
  LatoHeavy: "Lato_Heavy",
  LatoBlack: "Lato-Black",
  LatoReglar: "Lato-Regular",
  AbrilFatfaceRegular: "AbrilFatface_Regular",
  LexendBold: "Lexend_Bold",
  LexendLight: "Lexend_Light",
  PlayfairDisplayBoldItalic: "PlayfairDisplay_BoldItalic",
  HelveticaBold: "Helvetica-Bold",
  HelveticaRegular: "Helvetica_Regular",
  SeravekRegular: "Seravek",
  SeravekBold: "Seravek_Bold",
  SeravekLight: "Seravek_Light",
  SeravekMedium: "Seravek_Medium",
  GreatVibesRegular: "GreatVibes_Regular",
  MerriweatherLight: "Merriweather_Light",
};

export default Strings;
