export const fonts = {
  RobotoBold: "Roboto-Bold",
  RobotoBoldItalic: "Roboto-BoldItalic",
  RobotoItalic: "Roboto-Italic",
  RobotoLight: "Roboto-Light",
  RobotoLightItalic: "Roboto-LightItalic",
  RobotoMediumItalic: "Roboto-MediumItalic",
  RobotoRegular: "Roboto-Regular",
  RobotoThin: "Roboto-Thin",
  RobotoThinItalic: "Roboto-ThinItalic",
  Roboto: "Roboto",
  RobotoMedium: "Roboto-Medium",
  RobotoBlack: "Roboto-Black",
  RobotoBlackItalic: "Roboto-BlackItalic",
  MontserratSemiBold : "Montserrat-SemiBold",
  MonotypeCorsiva: 'MonotypeCorsiva',
  MontserratBlack:"Montserrat-Black",
  MontserratBlackItalic:"Montserrat-BlackItalic",
  MontserratBold:"Montserrat-Bold",
  MontserratBoldItalic:"Montserrat-BoldItalic",
  MontserratExtraBold:"Montserrat-ExtraBold",
  MontserratExtraBoldItalic:"Montserrat-ExtraBoldItalic",
  MontserratExtraLight:"Montserrat-ExtraLight",
  MontserratExtraLightItalic:"Montserrat-ExtraLightItalic",
  MontserratItalicVariableFont_wght:"Montserrat-Italic-VariableFont_wght",
  MontserratItalic:"Montserrat-Italic",
  MontserratLight:"Montserrat-Light",
  MontserratLightItalic: "Montserrat-LightItalic",
  MontserratMedium: "Montserrat-Medium",
  MontserratMediumItalic: "Montserrat-MediumItalic",
  MontserratRegular : "Montserrat-Regular",
  MontserratSemiBoldItalic : "Montserrat-SemiBoldItalic",
  MontserratThin : "Montserrat-Thin",
  MontserratThinItalic : "Montserrat-ThinItalic",
  MontserratVariableFont_wght : "Montserrat-VariableFont_wght"
};
